detectors:
  IrresponsibleModule:
    enabled: false
  DuplicateMethodCall:
    enabled: false
  UtilityFunction:
    public_methods_only: true

directories:
  "app/controllers":
    InstanceVariableAssumption:
      enabled: false

exclude_paths:
  - db/migrate
  - vendor
  - bin/
